### PR TITLE
Issue#20 會員階級 

### PR DESCRIPTION
**Pull request by emma0620**
測試會員階級(發文十篇升一階, 追蹤20人升一階)
Note: 己軟刪除的文章不包含在計算文章數量內

請執行:
python manage.py migrate
python manage.py create_groups
python manage.py runserver

1. 訪客未登入時
image

2. 使用者登入後, 請發文十篇以上, 追蹤20人以上, 測試升級
3. 左上方的階級顯示會更新
image

### CODE REVIEW

**Comment by EricHsu521** [comment]
測試結果，文章內階級會因為發文數增加，但是左上方不會改變，沒有更新到
image

**Comment by EricHsu521** [comment]
測試結果，畫面會狂閃，進入無窮迴圈
1. System check identified no issues (0 silenced).
September 17, 2024 - 14:16:09
Django version 5.1.1, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[17/Sep/2024 14:16:11] "GET / HTTP/1.1" 200 49893
[17/Sep/2024 14:16:11] "GET /static/styles/style.css HTTP/1.1" 304 0
[17/Sep/2024 14:16:11] "GET /static/scripts/app.js HTTP/1.1" 200 344231
[17/Sep/2024 14:16:11] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:12] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:12] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:13] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:13] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:13] "GET / HTTP/1.1" 200 49891
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:13] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:13] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:13] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245
[17/Sep/2024 14:16:14] "GET / HTTP/1.1" 200 49890
[17/Sep/2024 14:16:14] "GET /update-left-nav-bar/ HTTP/1.1" 200 6245

**Comment by EricHsu521** [comment]
測試結果ok ，但需要把所有註解拿掉 (例如: # 確保只對新創建的使用者進行操作)

image

**Review by EricHsu521 — DISMISSED** [review]

**Review by LianSongYang — APPROVED** [review]
測試ok

**Comment by KANG0918** [comment]
測試會員階級(發文十篇升一階, 追蹤20人升一階)
預設LV.0~LV49

查看資料庫user.group有沒有己建立 LV.0~LV49，請問這步驟如何執行？若是只是打開，裡面應該會是空的。

**Review by KANG0918 — DISMISSED** [review]

**Comment by EricHsu521** [comment]
測試結果
我登入網站的時候有90點會員點數，但是階級是LV 0
image

**Comment by EricHsu521** [comment]
測試ok

**Review by EricHsu521 — DISMISSED** [review]

**Review by jenjiunsu — APPROVED** [review]
測試ok

**Pull request closed without merging**
